let Bestseller = [
  {
    id: "Cake1",
    name: "T-pang Crepe Cake",
    price: 45,
    desc: "หอมอร่อยมั้ง",
    img: "images/cake-page/crepecake1.jpg",
  },
  {
    id: "Cake3",
    name: "Strawberry Creame Cakes",
    price: 60,
    desc: "ดีที่ไม่เน่า",
    img: "images/cake-page/cake2.png",
  },
  {
    id: "Best3",
    name: "Chocolate Crepe Cakes",
    price: 50,
    desc: "อย่าทิ้งเกิน 2 วันไม่งั้นมดขึ้น",
    img: "https://img.buzzfeed.com/video-api-prod/assets/bf889412d88f4cfc88748b46b5b72943/fb8.jpg?resize=1200:*",
  },
  {
    id: "icescreamcake1",
    name: "Oreo Ice Creame Cake",
    price: 80,
    desc: "กินวันนี้ ขี้พน.",
    img: "images/cake-page/ice1.jpg",
  },
];
let neww = [
  {
    id: "new1",
    name: "Blue Berry Cake (1 piece)",
    price: 50,
    desc: "เค้กบูลเบอลี่ ทางร้านจะเน้นรสชาติไปทางหวาน อมเปรี้ยวหน่อยครับ ด้านในจะสอดไส้ด้วยบูลเบอลี่เเละครัมเบิ้ลกรอบๆ เเทรกอยู่ด้านใต้ครับ",
    img: "images/index-page/blueberrycake.jpeg",
  },
  {
    id: "new2",
    name: "Chiffon Butter Cake (1 piece)",
    price: 80,
    desc: "เค้กชีพฟ่อนนุ่มๆ เมนูใหม่ของทางร้านเลยครับ ทำผิดพลาดมาหลายครั้งกว่าจะได้สูตรที่ลงตัวครับผม เชิญรับประทานกันได้เลยครับ",
    img: "images/index-page/chiffon.jpg",
  },
  {
    id: "new3",
    name: "Misu Moji Sou (1 box)",
    price: 75,
    desc: "Moji หยดน้ำสูตรจากเน็ตผสมกับทางร้านครับ พร้อมน้ำตาลทรายเเดงโรยด้านบน ของมาใหม่ของทางร้านเลยครับ เชิญรับประทานกันได้เลยครับ",
    img: "images/index-page/moji.jpeg",
  },
  {
    id: "new4",
    name: "Croissant Spinach Cream Cheese (1 piece)",
    price: 400,
    desc: "อร่อยลืมเมีย",
    img: "images/index-page/Spinach_Croissant2.webp",
  },
];

// pagecake
let Cake = [
  {
    id: "Cake1",
    name: "T-pang Crepe Cake",
    price: 45,
    desc: "หอมอร่อยมั้ง",
    img: "images/cake-page/crepecake1.jpg",
  },
  {
    id: "Cake2",
    name: "Strawberry Chesecake",
    price: 60,
    desc: "ดีที่ไม่เน่า",
    img: "images/cake-page/cake1.jpeg",
  },
  {
    id: "Cake3",
    name: "Strawberry Creame Cakes",
    price: 60,
    desc: "ดีที่ไม่เน่า",
    img: "images/cake-page/cake2.png",
  },
  {
    id: "Cake4",
    name: "Matcha mint Crepe Cakes",
    price: 55,
    desc: "อย่าทิ้งเกิน 2 วันไม่งั้นมดขึ้น",
    img: "images/cake-page/crepecake3.jpeg",
  },
  {
    id: "Cake5",
    name: "Rainbow Crepe Cake",
    price: 45,
    desc: "หอมอร่อยมั้ง",
    img: "images/cake-page/crepecake5.jpg",
  },
];

let icecreamecake = [
  {
    id: "icescreamcake1",
    name: "Oreo Ice Creame Cake",
    price: 100,
    desc: "หอมหวาน",
    img: "images/cake-page/ice1.jpg",
  },
  {
    id: "icescreamcake2",
    name: "Lemon Ice Creame Cake",
    price: 100,
    desc: "ขนมไข่",
    img: "images/cake-page/ice2.webp",
  },
  {
    id: "icescreamcake3",
    name: "Matcha Ice Creame Cake",
    price: 100,
    desc: "ขมปังหน้าหมา",
    img: "images/cake-page/ice3.jpeg",
  },
  {
    id: "icescreamcake4",
    name: "Strawberry Cake",
    price: 120,
    desc: "อร่อยลืมเมีย",
    img: "images/cake-page/ice4.webp",
  },
  {
    id: "icescreamcake5",
    name: "Matcha Crepe Cake",
    price: 120,
    desc: "หอมหวาน",
    img: "images/cake-page/ice5.jpeg",
  }
];

let cookies = [
  {
    id: "cookies1",
    name: "Chocolate Chip Cookie",
    price: 50,
    desc: "นี่เป็น Chocolate Chip Cookie ที่มีวิธีการทำง่ายๆแต่ไม่ใช่คุกกี้ที่อบจนกรอบแต่เป็นคุกกี้ที่มีความนุ่มอยู่ในตัวเมื่อกัดลงไป เป็นคุกกี้ที่แสนจะธรรมดาแต่ทางร้านเราใช้เวลาในการทำมันอย่างตั้งใจต้องขอบอกว่าต้องลองกรอบนอกนุ่มใน",
    img: "images/cookie-page/1.jpg",
  },
  {
    id: "cookies2",
    name: "Monster Cookies",
    price: 75,
    desc: "เจ้าคุ้กกี้หน้าตาประหลาดสีฟ้าชิ้นนี้ มีส่วนผสมของ Chocolate Chip, Oreos สับเป็นชิ้นเล็กๆ และไส้ Chocolate ที่ละลายอยู่ตรงกลางเมื่อกัดลงไปเป็นคุกกี้ประเภทที่มีความนุ่มนิ่มอีกทั้งยังมีส่วนผสมของคุกกี้ที่เอามาสับเป็นชิ้นเล็กๆเป็นคุกกี้ที่มีความหลากหลายในส่วนผสมของตัวมันเอง",
    img: "images/cookie-page/2.jpg",
  },
  {
    id: "cookies3",
    name: "Frosted Sugar Cookies",
    price: 50,
    desc: "เป็นคุกกี้แบบนุ่มอีกตัวนึงของทางร้าน โปะหน้าด้วยน้ำตาลและครีมที่เป็นส่วนผสมหลักเพื่อให้ความหวานกับตัวคุกกี้ดั่งชื่อของมัน มีสีสันสด สวยงาม มีความอร่อยอย่างมากเหมาะกับลูกค้าที่ชื่นชอบความหวานเป็นทุนเดิมอยู่แล้ว",
    img: "images/cookie-page/3.jpg",
  },
  {
    id: "cookies4",
    name: "Peanut Butter Blossoms",
    price: 80,
    desc: "คุกกี้แบบนิ่มที่มี Chocolate หนึบหนับอยู่ตรงกลางเป็นคุกกี้ที่เป็นขวัญใจของชาวอเมริกันทางร้านได้ให้ความสนใจกับคุกกี้ตัวนี้จึงได้ลองทำเพื่อนำมาขายให้กับลูกค้าชาวไทย และหากลูกค้าชื่อชอบเนยถั่วยิ่งต้องลองเพราะตัวคุกกี้มีส่วนผสมของเนยถั่วอยู่ด้วย",
    img: "images/cookie-page/4.jpg",
  },
  {
    id: "cookies5",
    name: "Ube Crinkle Cookies",
    price: 120,
    desc: "เป็นคุกกี้ที่ทำมาจากมันม่วงที่เอาไว้ใส่ในของหวานโดยเฉพาะ ซึ่งนำเข้ามาจากประเทศ ฟิลิปปินส์ โดยเฉพาะมีเฉดสีในตัวคุกกี้เป็นเอกลักษณ์คือสีม่วงมีความหวานอย่างมากในตัวคุกกี้ชิ้นนี้ทางร้านได้ทำให้มีความนุ่มมากกว่ากรอบต้องบอกเลยว่าสายของหวานและสายสุขภาพจะต้องถูกใจอย่างมากเพราะนอกจากความอร่อยแล้วยังได้ ประโยชน์ อย่างวิตามิน และช่วยเพิ่มการต้านทานมะเร็งอีกด้วย",
    img: "images/cookie-page/5.jpg",
  },
  {
    id: "cookies6",
    name: "Fortune Cookies",
    price: 40,
    desc: "ตามชื่อของคุกกี้ คุกกี้ชนิดนี้เรียกว่าคุกกี้เสี่ยงทายที่ร้านอาหารจันมักจะมีกันเมื่อทำนายดวงของด้วยเองทางร้านของเราเลยอยากจะขายเป็นชุดเพื่อให้ลูกค้านำไปแบ่งปันกับครอบครัวหรือคนใกล้ตัว ทางร้านยังได้พัฒนาตัวคุกกี้ให้มีความกรอบมากยิ่งขึ้นและความหอมของเนยอีกด้วย",
    img: "images/cookie-page/fc.webp",
  }
];

// page drink
let Milk = [
  {
    id: "milk1",
    name: "Vanilla Milk",
    price: 40,
    desc: "นมวานิลลาหอมนุ่มละมุน",
    img: "https://recipemarker.com/wp-content/uploads/2021/01/Warm-Vanilla-Milk-Recipe-225x225.jpg",
  },
  {
    id: "milk2",
    name: "Chocolate Milk",
    price: 35,
    desc: "นมช็อกโกแลตหวานอร่อย",
    img: "https://wholefoodsoulfoodkitchen.com/wp-content/uploads/2022/06/healthy-chocolate-milk-with-cocoa-powder-2-500x500.jpg",
  },
  {
    id: "milk3",
    name: "Banana Milk",
    price: 30,
    desc: "นมกล้วยสุดหอมหวาน",
    img: "https://drivemehungry.com/wp-content/uploads/2022/08/korean-banana-milk-1-500x500.jpg",
  },
  {
    id: "milk4",
    name: "Strawberry Milk",
    price: 30,
    desc: "นมสตรอว์เบอร์รี่สุดอร่อย",
    img: "https://bakingmischief.com/wp-content/uploads/2018/11/homemade-strawberry-milk-recipe-image-square-500x500.jpg",
  },
  {
    id: "milk5",
    name: "Blueberry Milk",
    price: 45,
    desc: "นมบลูเบอร์รีเปรี้ยวอมหวาน",
    img: "https://www.sugarsaltmagic.com/wp-content/uploads/2022/08/Blueberry-Milk-8FEAT-500x500.jpg",
  },
  {
    id: "milk6",
    name: "Almond Milk",
    price: 60,
    desc: "นมอัลมอนด์หอมอร่อย",
    img: "https://foolproofliving.com/wp-content/uploads/2020/04/Almond-Milk-from-almond-butter-recipe-image-500x500.jpg",
  },
];
let Juice = [
  {
    id: "juice1",
    name: "Apple Juice",
    price: 50,
    desc: "น้ำเเอปเปิ้ลหวานเปรี้ยว",
    img: "https://www.goodnature.com/wp-content/uploads/2021/07/apple-juice-hero-500x500.jpg",
  },
  {
    id: "juice2",
    name: "Grape Juice",
    price: 80,
    desc: "น้ำองุ่นคุณภาพดี",
    img: "https://healthyrecipes101.com/wp-content/uploads/2020/10/How-Much-Grape-Juice-per-Day-500x500.jpg",
  },
  {
    id: "juice3",
    name: "Orange Juice",
    price: 60,
    desc: "น้ำส้มสายน้ำผึ้ง",
    img: "https://www.thebutterhalf.com/wp-content/uploads/2022/08/Orange-Juice-13-500x500.jpg",
  },
  {
    id: "juice4",
    name: "Pineapple Juice",
    price: 65,
    desc: "น้ำสับปะรดเปรี้ยวเเละอร่อย",
    img: "https://healthyrecipes101.com/wp-content/uploads/2020/10/Calories-in-Added-Sugar-Free-Pineapple-Juice-500x500.jpg",
  },
  {
    id: "juice5",
    name: "Blueberry Juice",
    price: 65,
    desc: "น้ำบลูเบอร์รี่หวานอร่อย",
    img: "https://www.attainable-sustainable.net/wp-content/uploads/2022/07/blueberry-juice-1-735x735.jpg",
  },
  {
    id: "juice6",
    name: "Cherry Juice",
    price: 80,
    desc: "น้ำเชอร์รี่สุดหวาน",
    img: "https://thebrilliantkitchen.com/wp-content/uploads/2022/06/Tart-Cherry-Juice-500x500.jpg",
  },
  {
    id: "juice7",
    name: "Pomegranate Juice",
    price: 70,
    desc: "น้ำทับทิมหอมหวานอร่อย",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/pomegranate-juice-recipe-500x500.jpg",
  },
  {
    id: "juice8",
    name: "Watermelon Juice",
    price: 75,
    desc: "น้ำแตงโมหวานฉ่ำ",
    img: "https://masalaandchai.com/wp-content/uploads/2022/04/Fresh-Watermelon-Juice-500x500.jpg",
  },
];
let Tea = [
  {
    id: "tea1",
    name: "Thai Tea",
    price: 80,
    desc: "ชาไทยหวานมัน",
    img: "https://www.aimeemars.com/wp-content/uploads/2020/06/Thai-Iced-Tea-in-Plastic-Cup-500x500.jpg",
  },
  {
    id: "tea2",
    name: "Black Tea",
    price: 90,
    desc: "ชาดำหอมละมุน",
    img: "https://www.sharmispassions.com/wp-content/uploads/2021/05/BlackTea4-500x500.jpg",
  },
  {
    id: "tea3",
    name: "Turkish Tea",
    price: 100,
    desc: "ชาตุรกีหอมหวาน",
    img: "https://cf.shopee.co.th/file/8daf13e1d3aa0610d6c37f9ad5070e8d",
  },
  {
    id: "tea4",
    name: "Hong Kong Milk Tea",
    price: 85,
    desc: "ชานมฮ่องกงอร่อยหวานมัน",
    img: "https://thewoksoflife.com/wp-content/uploads/2019/02/hong-kong-milk-tea-500x500.jpg",
  },
  {
    id: "tea5",
    name: "Pu'er Tea",
    price: 45,
    desc: "ชาผู่เอ๋อร์ฝาดเปรี้ยวสดใหม่",
    img: "https://th-live-01.slatic.net/p/f65d87dc3ea852431e2ed4145e11ce90.jpg",
  },
];
let Coffee = [
  {
    id: "coffee1",
    name: "Espresso",
    price: 150,
    desc: "เอสเพรสโซรสชาติเข้มข้นหนักแน่น",
    img: "https://coffeeatthree.com/wp-content/uploads/espresso-2-500x500.jpg",
  },
  {
    id: "coffee2",
    name: "Americano",
    price: 130,
    desc: "อเมริกาโนเข้มหวานกลมกล่อม",
    img: "https://assets.tokko.io/92bba6d3-c1c7-4d3a-a6d3-4a55c6c8d549/products/images/070f1545-7343-4986-b4ff-015746591225",
  },
  {
    id: "coffee3",
    name: "Latte",
    price: 120,
    desc: "ลาเต้หวานมันกลมกล่อม",
    img: "https://bakingmischief.com/wp-content/uploads/2019/05/dulce-de-leche-latte-image-square-500x500.jpg",
  },
  {
    id: "coffee4",
    name: "Cappuccino",
    price: 140,
    desc: "คาปูชิโน่เข้มข้นและหวานมัน",
    img: "https://www.cremedevape.com/WebRoot/Store/Shops/yxve46fvrnud/5B0E/8491/4F6F/6E6B/391C/0A28/1056/5CEF/Cappucino.jpg",
  },
  {
    id: "coffee5",
    name: "Mocha",
    price: 170,
    desc: "มอคค่าหวานมันกลมกล่อม",
    img: "https://bellyfull.net/wp-content/uploads/2020/06/Iced-Coffee-Mocha-Frappuccino-blog-2-500x500.jpg",
  },
  {
    id: "coffee6",
    name: "Macchiato",
    price: 160,
    desc: "มัคคิอาโต้กลมกล่อม",
    img: "http://cdn.shopify.com/s/files/1/0587/8795/4884/products/CaramelMacchiato_18ca5121-fa79-4e8b-9e68-fbbac83862ff.png?v=1630346987",
  },
  {
    id: "coffee7",
    name: "Flat White",
    price: 140,
    desc: "แฟลทไวท์สุดเข้มข้น",
    img: "https://cdn.shopify.com/s/files/1/0569/9180/9708/products/Flat-white-coffee_500x.jpg?v=1626925713",
  },
  {
    id: "coffee8",
    name: "Affogato",
    price: 180,
    desc: "อัฟโฟกาโตหอมหวานมันเเละกลมกล่อม",
    img: "https://www.aspicyperspective.com/wp-content/uploads/2021/11/affogato-recipe-4-500x500.jpg",
  },
];
let snack = [
  {
    id: "snack1",
    name: "Fries",
    price: 50,
    desc: "เฟรนช์ฟรายส์จะเสิร์ฟร้อนกรอบนอกเเละนุ่มใน และโดยทั่วไปจะรับประทานเป็นส่วนหนึ่งของมื้อกลางวันหรือมื้อค่ำ หรือรับประทานเป็นของว่าง ",
    img: "https://www.dinneratthezoo.com/wp-content/uploads/2020/01/baked-french-fries-5-500x500.jpg",
  },
  {
    id: "snack2",
    name: " Gyudon Beef Rice Bowl",
    price: 80,
    desc: "เป็นอาหารญี่ปุ่นที่ประกอบด้วยชามข้าวราดหน้าด้วยเนื้อวัวและหัวหอมเคี่ยวอย่างอ่อนโยน ซอสหวานปรุงรสด้วยดาชิ (สต๊อกปลาและสาหร่าย ) โชยุและมิริน (ไวน์ข้าว หวาน ) เสิร์ฟพร้อมท็อปปิ้ง เช่น ไข่ดาวน้ำดิบหรือไข่ ลวก หัว หอมเวลส์ ",
    img: "https://img.wongnai.com/p/1920x0/2018/05/03/6f7e1b97ab454c66812c064ab128ba29.jpg",
  },
  {
    id: "snack3",
    name: "Salted Egg Lava Cake (5 piece)",
    price: 150,
    desc: "ขนมเปี๊ยะนุ่มๆ พร้อมไส้ลาวาไข่เค็มข้างใน",
    img: "https://howtocookhub.com/wp-content/uploads/2022/07/%E0%B8%82%E0%B8%99%E0%B8%A1%E0%B9%80%E0%B8%9B%E0%B8%B5%E0%B9%8A%E0%B8%A2%E0%B8%B0-%E0%B9%84%E0%B8%82%E0%B9%88%E0%B9%80%E0%B8%84%E0%B9%87%E0%B8%A1-%E0%B8%A5%E0%B8%B2%E0%B8%A7%E0%B8%B2.jpg",
  },
  {
    id: "snack4",
    name: "Mathca Moji with Red Bean (3 piece)",
    price: 400,
    desc: "โมจินุ่มๆพร้อมไส้ถั่วเเดงด้านใน อร่อยสดใหม่ทุกวัน",
    img: "https://www.honestfoodtalks.com/wp-content/uploads/2022/07/green-tea-mochi.jpg",
  },
];
let Bread = [
  {
    id: "bread1",
    name: "Thai Tea",
    price: 80,
    desc: "ชาไทยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "bread2",
    name: "Black Tea",
    price: 90,
    desc: "ชาดำหอมละมุน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
  {
    id: "bread3",
    name: "Turkish Tea",
    price: 100,
    desc: "ชาตุรกีหอมหวาน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "bread4",
    name: "Hong Kong Milk Tea",
    price: 85,
    desc: "ชานมฮ่องกงอร่อยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
  {
    id: "bread5",
    name: "Pu'er Tea",
    price: 45,
    desc: "ชาผู่เอ๋อร์ฝาดเปรี้ยวสดใหม่",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "bread6",
    name: "Hong Kong Milk Tea",
    price: 85,
    desc: "ชานมฮ่องกงอร่อยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
];
let Croissant = [
  {
    id: "croissant1",
    name: "Thai Tea",
    price: 80,
    desc: "ชาไทยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "croissant2",
    name: "Black Tea",
    price: 90,
    desc: "ชาดำหอมละมุน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
  {
    id: "croissant3",
    name: "Turkish Tea",
    price: 100,
    desc: "ชาตุรกีหอมหวาน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "croissant4",
    name: "Hong Kong Milk Tea",
    price: 85,
    desc: "ชานมฮ่องกงอร่อยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
  {
    id: "croissant5",
    name: "Pu'er Tea",
    price: 45,
    desc: "ชาผู่เอ๋อร์ฝาดเปรี้ยวสดใหม่",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "croissant6",
    name: "Hong Kong Milk Tea",
    price: 85,
    desc: "ชานมฮ่องกงอร่อยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
];
let Baguette = [
  {
    id: "baguette1",
    name: "Thai Tea",
    price: 80,
    desc: "ชาไทยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "baguette2",
    name: "Black Tea",
    price: 90,
    desc: "ชาดำหอมละมุน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
  {
    id: "baguette3",
    name: "Turkish Tea",
    price: 100,
    desc: "ชาตุรกีหอมหวาน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "baguette4",
    name: "Hong Kong Milk Tea",
    price: 85,
    desc: "ชานมฮ่องกงอร่อยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
  {
    id: "baguette5",
    name: "Pu'er Tea",
    price: 45,
    desc: "ชาผู่เอ๋อร์ฝาดเปรี้ยวสดใหม่",
    img: "https://cms.dmpcdn.com/food/2020/04/03/2270bf60-7596-11ea-865e-99779963a9e7_original.jpg",
  },
  {
    id: "baguette6",
    name: "Hong Kong Milk Tea",
    price: 85,
    desc: "ชานมฮ่องกงอร่อยหวานมัน",
    img: "https://cms.dmpcdn.com/food/2020/04/03/22892960-7596-11ea-b4e9-0984d8e8648f_original.jpg",
  },
];
